//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDemoExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Access
    {
        public int id { get; set; }
        public int guest_id { get; set; }
        public int room_id { get; set; }
        public string access_card_code { get; set; }
        public string status { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
